language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
script:
- yarn lint
after_success:
- DIR=$TRAVIS_BUILD_DIR yarn deploy
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
# Decrypt keyfile.json
- openssl aes-256-cbc -K $encrypted_92f353705aa7_key -iv $encrypted_92f353705aa7_iv
  -in keyfile.json.enc -out keyfile.json -d
# Install Terraform
- mkdir -p $HOME/bin
- wget https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_386.zip -O terraform.zip
- unzip terraform.zip
- chmod +x terraform
- mv terraform $HOME/bin
- export PATH=$HOME/bin:$PATH
