service: gcp-package-registry

provider:
  name: google
  runtime: nodejs
  project: serlo-assets
  credentials: ${env:DIR}/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  resolve:
    handler: resolve
    events:
      - http: path

resources:
 resources:
   - type: storage.v1.bucket
     name: package-registry
