service: gpc-package-registry

provider:
  name: google
  runtime: nodejs
  project: serlo-assets
  credentials: ${env:CWD}/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  resolve:
    handler: resolve
    events:
      - http: path
